### ISSUE TITLE
ModuleNotFoundError: No module named 'nemo'

### ISSUE THREAD

**Issue by nourbouaziz98** [instadeepai/tunbert#2]
While running the command ``` python models/bert-nvidia/bert_finetuning_SA_DC.py --config-name "sentiment_analysis_config" model.language_model.lm_checkpoint="/path/to/checkpoints/PretrainingBERTFromText--end.ckpt" model.train_ds.file_path="/path/to/train.tsv" model.validation_ds.file_path="/path/to/valid.tsv" model.test_ds.file_path="/path/to/test.tsv" ``` to fine-tune TunBERT-PyTorch on the SA task, I had the following error 
![image](https://user-images.githubusercontent.com/86783579/125266061-5411fb80-e2fd-11eb-8e27-9f803f6ed85b.png)
I tried to install NeMo several times, but the error still persists.

**Comment by fourat-bs** [comment]
@nourbouaziz98 
try this:
 !pip install git+https://github.com/NVIDIA/NeMo.git

**Comment by MalekBezzina** [comment]
> @nourbouaziz98
> try this:
> !pip install git+https://github.com/NVIDIA/NeMo.git
 i tried following your instruction and I got this error:

D:\tunbert-main>pip install git+https://github.com/NVIDIA/NeMo.git
Collecting git+https://github.com/NVIDIA/NeMo.git
  Cloning https://github.com/NVIDIA/NeMo.git to c:\users\delli3~1\appdata\local\temp\pip-umlhwszh-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\DELLI3~1\AppData\Local\Temp\pip-umlhwszh-build\setup.py", line 106
        f'--use-parentheses --line-width={__LINE_WIDTH} -rc -ws'
        ^
    SyntaxError: invalid syntax

**Comment by nourbouaziz98** [comment]
@fourat-bs 

> @nourbouaziz98
> try this:
> !pip install git+https://github.com/NVIDIA/NeMo.git

Thank you for the suggestion, but it's still not working. It shows the same error

**Comment by AltafAllahAbbassi** [comment]
Same here , any solution ?

**Comment by fourat-bs** [comment]
if you guys tried pip install nemo_toolkit[all] and the error remains that mean your script is looking for modules in the wrong place , make sure you’re installing the package in the right environment. the script is working fine for me both on colab and locally, if the problem still occur you can email me on mohamedfouratb@gmail.com and we try to fix the issue.

**Comment by AaronCWacker** [comment]
Mine was missing Cython after fresh install running python 3.10...  Fixed with pip install Cython.  Then missing Microsoft Visual C++ 14.0.  Fixed with reinstall of Microsoft Visual C++ 14.0 from runtime install page for PC:  https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170  and build tools here:  https://visualstudio.microsoft.com/visual-cpp-build-tools/  Then pesq fails.  Still working on it.

**Comment by RezuwanHassan262** [comment]
> 

It worked for me, thanks!

**Comment by Firashs01** [comment]
If anyone can provide me with an example of working with TunnBERT, I have a project and I'm currently facing a roadblock. Thank you in advance

**Comment by fourat-bs** [comment]
@Firashs01 that's my [notebook](https://colab.research.google.com/drive/19txh_-DUNuDge28V_WPBdUbyE8HN1_zC?usp=sharing) that I've used back in 2021, it clones my fork of Tunbert and uses fixed versions of the libraries beneath.

**Comment by Firashs01** [comment]
@fourat-bs  ok thanks so much

**Comment by mayur-ml** [comment]
ModuleNotFoundError: No module named 'hydra'
